import type { SidebarsConfig } from '@docusaurus/plugin-content-docs';

/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.
 */
const sidebars: SidebarsConfig = {
  // By default, Docusaurus generates a sidebar from the docs folder structure
  // tutorialSidebar: [{type: 'autogenerated', dirName: '.'}],

  // But you can create a sidebar manually
  docsSidebar: [
    {
      type: 'category',
      label: 'sokol-zig',
      link: { type: 'doc', id: 'sokol/index' },
      items: [
        'sokol/sgl',
      ],
    },
    {
      type: 'category',
      collapsed: false,
      label: 'imgui',
      // link: { type: 'doc', id: 'index' },
      items: [
        'imgui/dockspace',
      ],
    },
    {
      type: 'category',
      collapsed: false,
      label: 'wasm',
      // link: { type: 'doc', id: 'index' },
      items: [
        'wasm/emscripten',
      ],
    },
  ],
};

export default sidebars;
