name: wasm

on:
  push:
    branches:
      - master
    # Review gh actions docs if you want to further define triggers, paths, etc
    # https://docs.github.com/en/actions/using-workflows/workflow-syntax-for-github-actions#on
  workflow_dispatch:

# GITHUB_TOKEN のパーミッションを設定し、GitHub Pages へのデプロイを許可します
permissions:
  contents: read
  pages: write
  id-token: write

# 1 つの同時デプロイメントを可能にする
concurrency:
  group: 'pages'
  cancel-in-progress: true

jobs:
  deploy:
    name: Deploy to GitHub Pages
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      # build wasm
      - uses: goto-bus-stop/setup-zig@v2
      - name: clone sokol tools
        run: |
          git clone https://github.com/floooh/sokol-tools-bin.git
          sokol-tools-bin/bin/linux/sokol-shdc -i src/teapot.glsl -o src/teapot.glsl.zig -l glsl430:metal_macos:hlsl5:glsl300es:wgsl -f sokol_zig
      - name: build Wasm
        run: |
          zig build --summary all -Dtarget=wasm32-emscripten -Doptimize=ReleaseSmall
          mkdir -p docs/static/wasm
          cp zig-out/web/* docs/static/wasm/
          zig build docs --summary all -Dtarget=wasm32-emscripten -Doptimize=ReleaseSmall
          cp zig-out/doc/* docs/static/wasm/
      # docusaurus
      - uses: actions/setup-node@v3
        with:
          node-version: 18
      - name: Install dependencies
        run: |
          cd docs
          npm install
          npm run build
      # deploy
      - name: Setup Pages
        uses: actions/configure-pages@v3
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v2
        with:
          path: './docs/build'
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v2
